In [1]:
import pandas as pd
import numpy as np

In [2]:
print(np.nan)
print("It's used to print 'Not a number'")

nan
It's used to print 'Not a number'

In [3]:
print(pd.NaT)
print("It's used to print 'Not a Timestamp'")

NaT
It's used to print 'Not a Timestamp'

In [4]:
np.nan == np.nan

False

In [5]:
np.nan is np.nan

True

In [6]:
myvar = np.nan
myvar is np.nan

True

In [ ]:
df = pd.read_csv('C:/Machine Learning Journey/Datasets/Pandas/tips.csv')

In [8]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

Let's see how to check and select the NaN values

In [9]:
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [10]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

Check for rows where NaN values are not present in pre_movie_score and post_movie_score

In [11]:
df[df['pre_movie_score'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [12]:
df[(df['pre_movie_score'].isnull()) & (df['first_name'].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

### Keep the data

### Drop the data

### Fill the data

## Keep the data:

In [13]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

## Drop the data:

In [14]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: Axis = 0,
    how: AnyAll | lib.NoDefault = <no_default>,
    thresh: int | lib.NoDefault = <no_default>,
    subset: IndexLabel | AnyArrayLike | None = None,
    inplace: bool = False,
    ignore_index: bool = False
) -> DataFrame | None method of pandas.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or iterable of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "name": ["Alfred", "Batman", "Catwoman"],
    ...         "toy": [np.nan, "Batmobile", "Bullwhip"],
    ...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    ...     }
    ... )
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis="columns")
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how="all")
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=["name", "toy"])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [15]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

But now we want to remove only that entire NaN row:

In [16]:
df.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

It means, go ahead and drop all the rows with NaN unless you encounter one not a NaN value

In [17]:
df.dropna(thresh=5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

Here, Hugh is gone because it doesn't have 5 non-null values

In [18]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [19]:
df.dropna(axis = 0)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

Subset argument:

In [20]:
df.dropna(subset = ['last_name'])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

Here, there's only 1 row with missing last name, so that got removed

## Fill the data:

In [21]:
help(df.fillna)

Help on method fillna in module pandas.core.generic:

fillna(
    value: Hashable | Mapping | Series | DataFrame,
    *,
    axis: Axis | None = None,
    inplace: bool = False,
    limit: int | None = None
) -> Self method of pandas.DataFrame instance
    Fill NA/NaN values with `value`.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        This is the maximum number of entries along the entire axis
        where NaNs will be filled. Must be greater than 0 if not None.

    Returns
    -------
    Series/DataFrame
        Object with missing values filled.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Notes
    -----
    For non-object dtype, ``value=None`` will use the NA value of the dtype.
    See more details in the :ref:`Filling missing data<missing_data.fillna>`
    section.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     [
    ...         [np.nan, 2, np.nan, 0],
    ...         [3, 4, np.nan, 1],
    ...         [np.nan, np.nan, np.nan, np.nan],
    ...         [np.nan, 3, np.nan, 4],
    ...     ],
    ...     columns=list("ABCD"),
    ... )
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [22]:
df.fillna("New Value")

  first_name  last_name        age        sex pre_movie_score post_movie_score
0        Tom      Hanks       63.0          m             8.0             10.0
1  New Value  New Value  New Value  New Value       New Value        New Value
2       Hugh    Jackman       51.0          m       New Value        New Value
3      Oprah    Winfrey       66.0          f             6.0              8.0
4       Emma      Stone       31.0          f             7.0              9.0

If we fill with a string, what Pandas does is, it converts all the values, such as 63 here as a string instead of its original datatype.

In [23]:
df['pre_movie_score'] = df['pre_movie_score'].fillna(0)

In [24]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               NaN
2       Hugh   Jackman  51.0    m              0.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

Let's try filling them with mean

In [25]:
mean = df['pre_movie_score'].mean()
mean

np.float64(4.2)

In [28]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    0.0
2    0.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [29]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               NaN
2       Hugh   Jackman  51.0    m              0.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [31]:
df.fillna(df.mean())

TypeError: Cannot perform reduction 'mean' with string dtype

That is old way, this is new Pandas:

In [39]:
df['pre_movie_score'] = df['pre_movie_score'].fillna(df['pre_movie_score'].mean())
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

To insert mean of each columns in their respective places:

In [42]:
df.fillna(df.mean(numeric_only=True), inplace=True)

  first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1        NaN       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0

Let's copy and paste a dictionary from lecture notes and convert into series:

In [43]:
airline_tix = {'first':100,'business':np.nan,'economy-plus':50,'economy':30}

In [46]:
ser = pd.Series(airline_tix)
ser

first           100.0
business          NaN
economy-plus     50.0
economy          30.0
dtype: float64

In [47]:
ser.interpolate()

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64

interpolate() is used to fill missing (NaN) values by estimating them from nearby values, instead of using a fixed value like mean or median.